
[package]
name = "whatsapp-rust"
version = "0.1.0"
edition = "2024"
[workspace]
members = [".", "wacore", "waproto"]

[workspace.dependencies]
libsignal-protocol = { git = "https://github.com/jlucaso1/libsignal", branch = "working" }
rand = "0.9"
rand_core = "0.9"
waproto = { path = "./waproto" }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = { version = "0.10.2", features = [
    "aes",
    "alloc",
], default-features = false }
anyhow = { version = "1.0", default-features = false }
async-trait = "0.1.88"
bincode = { version = "2.0.1", features = ["serde"] }
bytes = { version = "1.5", default-features = false }
cbc = { version = "0.1.2", features = ["alloc"] }

# Time handling
chrono = { version = "0.4" }
clap = { version = "4.5", features = ["derive"] }
dashmap = "6.1.0"
diesel = { version = "2.2.12", features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.2.0"
env_logger = { version = "0.11", default-features = false }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
futures-util = { version = "0.3.31", default-features = false }

hex = { version = "0.4", features = ["alloc"], default-features = false }
hkdf = "0.12.3"
libsignal-protocol = { workspace = true }
log = "0.4.27"
prost = { version = "0.14.1", default-features = false }

# Cryptography
rand = { workspace = true }
rand_core = { workspace = true }
scopeguard = "1.2"
serde = { version = "1.0.188", features = ["derive"] }
serde-big-array = "0.5.1"
serde_json = "1.0"
sha2 = "0.10.6"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = [
    "fs",
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-tungstenite = { version = "0.27.0", features = ["native-tls"] }
ureq = "3.0.12"
urlencoding = "2.1"
wacore = { path = "./wacore" }
waproto = { workspace = true }

[dev-dependencies]
base64 = { version = "0.22.1", default-features = false }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "optimization_bench"
harness = false

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[[test]]
name = "group_e2e_self_test"
path = "tests/group_e2e_self_test.rs"
harness = true
