[package]
name = "wacore-binary"
version = "0.1.0"
edition = "2024"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz', '--enable-bulk-memory', '--enable-nontrapping-float-to-int']

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
wasm = ["wasm-bindgen", "serde-wasm-bindgen", "serde", "wee_alloc"]
serde = ["dep:serde"]

[dependencies]
flate2 = { version = "1.0", default-features = false, features = ["zlib-rs"] }
phf = { version = "0.12.1", features = ["macros"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
wasm-bindgen = { version = "0.2.100", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[build-dependencies]
phf_codegen = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
